### PR TITLE
[MINSC] Generate the documentation automatically during CI pipelines

### PR DESCRIPTION
**Pull request by giovanni-prestipino**
I have added the generation of the documentation in the CI pipeline.

### CODE REVIEW

**Review by nromeoarena — APPROVED** [review]
ok

**Comment by deusebio** [comment]
Can you put the same command in the Makefile? I put the simplified version (less elegant) "cd sphinx && make html", but I like your solution

**Review by deusebio — APPROVED** [review]
Just a minor, good to go

**Comment by giovanni-prestipino** [comment]
> Can you put the same command in the Makefile? I put the simplified version (less elegant) "cd sphinx && make html", but I like your solution

**Review by NicolaDonelli — APPROVED** [review]
Fine by me

**Pull request merged**
