### PR TITLE
[closes #6] Added repository initialization script

### LINKED ISSUE #6: parentdir_prefix
I just realized that in the setup.cfg file there is this line:
```
parentdir_prefix = python-ci-template
```

To me, it seems quite annoying for a template to have the folder name hardcoded in the configuration file... isn't there a way to make this definition relative to the path where this file is placed (according to the template structure)?

### PR DESCRIPTION
**Pull request by ascartabelli**

### CODE REVIEW

**Review by NicolaDonelli — APPROVED** [review]
I am fine with the solution (especially I appreciate making @nromeoarena the default author of all our python projects!)

@deusebio could this be integrated in an "init" make command?

Depending on how we will choose to answer the structure question raised in issue #5  it could be worth adding to this part also the renaming of the src folder.

**Comment by ascartabelli** [comment]
> I am fine with the solution (especially I appreciate making @nromeoarena the default author of all our python projects!)

He did it himself and I didn't have the heart to replace him with a placeholder.

Seriously speaking: I added only one placeholder as an example. If we all agree on the solution I can update the PR with more.

**Review by nromeoarena — APPROVED** [review]
Fine with the implementation, please just add more placeholders, especially for my name as author, better to use a general one for CGnal team

**Comment by ascartabelli** [comment]
> Fine with the implementation, please just add more placeholders, especially for my name as author, better to use a general one for CGnal team

Is a placeholder there really needed though? Shouldn't be better to simply put "CGnal s.r.l." as the author and "info@cgnal.com" as the author's mail?

**Comment by nromeoarena** [comment]
Yes for example

**Comment by nromeoarena** [comment]
> > Fine with the implementation, please just add more placeholders, especially for my name as author, better to use a general one for CGnal team
> 
> Is a placeholder there really needed though? Shouldn't be better to simply put "CGnal s.r.l." as the author and "[info@cgnal.com](mailto:info@cgnal.com)" as the author's mail?

yes!

**Comment by ascartabelli** [comment]
Ok, I'll update the PR.

**Review by deusebio — APPROVED** [review]
Good to go!

**Pull request merged**
