### PR TITLE
[ISSUE-48;ISSUE-49;ISSUE-50] General improvement to Makefile

### LINKED ISSUE #48: Make commands uninstall local package
We just noticed that some make commands (all those commands depending on setup_ci and install_tag) remove the local package (i.e. the one currently under development in the repo, installed with `make install`) from the environment.
This is quite annoying, especially in contexts where one is developing a namespace package instead of a simple package (like we do with cgnal namespace) but I don't think it should happen in general.

The quickest solution should be to invert the priority of dependence from `make XXX: $(install_tag) setup_ci` to `make XXX:  setup_ci $(install_tag)`, but I am not completely sure about all the implications of this change.

### LINKED ISSUE #49: Make install do not re-install correctly the package
We just realized that `make install` does not correctly re-install the package.
In particular, if one runs `make mypy` removes the current package from the environment (since it syncs requirements_ci.txt after running the install_tag, as explained in issue #48 ) but running `make install` afterwards does nothing since it checks for the existence of the `make_cache/.install_tag` file and it actually exists.

@deusebio, I think that `make install` should not be cached at all, only `make dist` should.

### LINKED ISSUE #50: make install depends on setup
Thanks to @afalcioni I just realized that the `make install` command depends on the `setup` command. This implies that requirements.txt is installed before installing the package but this should not be needed since installing a package with pip should already install all its dependencies.

On the other hand, this behaviour could conflict with those commands that pre-require setup_ci since this implies that running install after setup_ci overwrites requirements_ci with requirements, removing some necessary package (e.g. pytest, mypy, flake8,...).

### PR DESCRIPTION
**Pull request by deusebio**
Implementing suggestions provided in the dedicated issues. Please just review that all points are covered

### CODE REVIEW

**Review by afalcioni — APPROVED** [review]
Fine for me

**Comment by NicolaDonelli** [comment]
On the same line of my previous comment I'd add that, even if it could be fine to "develop with closed requirements" (i.e. to use close requirements for `make install` which should be the way one installs things while developing), at least in the case of a package, it probably would be better to test with open requirements (thus, for packages, either the CI/CD workflows should be updated not to use make commands at all or we should create specific versions of make commands that use open requirements instead of closed ones).
Either way, we would not be able to quickly notice issues related to new releases of our dependencies.

**Review by NicolaDonelli — COMMENTED** [review]
I've got some doubts on the fact that we are always installing closed requirements.

Even if it could be fine to "develop with closed requirements" (i.e. to use close requirements for `make install` which should be the way a developer installs things while developing), at least in the case of a package, it probably would be better to test with open requirements (thus, for packages, either the CI/CD workflows should be updated not to use make commands at all or we should create specific versions of make commands that use open requirements instead of closed ones).
Either way, we would not be able to quickly notice issues related to new releases of our dependencies.

**Comment by deusebio** [comment]
I believe that as long as this package is concerned it would be best to keep things with closed requirements, which is the safest option. I understand that when dealing with packages other need may arise, but I believe this is a quite special case, not the default one

**Review by NicolaDonelli — APPROVED** [review]
I can agree that keeping the process with closed requirements is the safest solution but, as of now, it is also the less common use we made of this template (3 usages on my side, 3 packages).

In any case, it is something that should be addressed in a separate issue.

**Pull request merged**
